import { abrir, idle as _idle, shot as _shot, login as _login, salir, fin, BASE, OUT, errores } from './lib.mjs'
const { browser, page } = await abrir()
const PREFIX = 'cierre-'
const idle = () => _idle(page); const shot = n => _shot(page, PREFIX + n)
await _login(page, 'demo@bigsys.com.ar')
await page.click('button:has-text("Saltar")').catch(() => {})
// 1. Cliente del exterior
await page.goto(`${BASE}/clientes`); await idle(); await page.locator('button:has-text("Nuevo cliente")').first().click(); await page.waitForTimeout(300)
await page.fill('.fixed input.input >> nth=0', 'Importadora do Sul Ltda')
await page.selectOption('.fixed select.input >> nth=0', 'Exterior'); await page.waitForTimeout(200)
console.log('  campos exterior:', await page.locator('label:has-text("País (ARCA)")').count(), await page.locator('label:has-text("CUIT país")').count())
await page.selectOption('label:has-text("País (ARCA)") + select', '203'); await page.waitForTimeout(100)
console.log('  cuit país auto:', await page.locator('input[placeholder="55000002002"]').inputValue())
await page.fill('input[placeholder="CNPJ, RUT, VAT…"]', '12.345.678/0001-90')
await page.click('.fixed button:has-text("Guardar")'); await idle(); await page.waitForTimeout(400)
console.log('  cliente guardado:', await page.locator('text=Importadora do Sul').count() > 0)
// 2. Factura E
await page.goto(`${BASE}/comprobantes/nuevo`); await idle()
const cli = page.locator('input[placeholder^="Buscar cliente"]'); await cli.click(); await cli.fill('Importadora'); await page.waitForTimeout(500); await page.keyboard.press('Enter'); await page.waitForTimeout(300)
console.log('  tipo resuelto:', (await page.locator('text=Se emitirá como').textContent()).trim(), '· bloque exportación:', await page.locator('h2:has-text("Exportación (Factura E)")').count(), '· tilde ARCA:', await page.locator('text=Informar a ARCA').count())
await page.click('button:has-text("US$ Dólares")'); await page.fill('input[placeholder="Cotización"]', '1000')
await page.click('button:has-text("Agregar")'); const art = page.locator('input[placeholder^="Buscar artículo"]').first(); await art.click(); await art.fill('cem'); await page.waitForTimeout(500); await page.keyboard.press('Enter'); await page.waitForTimeout(300)
await page.locator('input[data-cant="0"]').fill('100'); await page.locator('input[data-precio="0"]').fill('12')
console.log('  IVA del ítem:', await page.locator('tbody select.input').first().inputValue(), '· total:', (await page.locator('.sticky .text-lg span.tabular-nums').textContent()).trim())
await page.fill('input[placeholder="Opcional"]', '26001EC01000123A')
await shot('01-factura-e')
await page.click('button:has-text("Emitir")'); await idle(); await page.waitForTimeout(700)
console.log('  emitida:', page.url().replace(BASE, ''), '·', (await page.locator('h1.page-title').textContent()).replace(/\s+/g, ' ').trim(), '·', (await page.locator('.badge').allTextContents()).map(t => t.trim()).filter(t => /CAE|simulado|Sin/.test(t)).join(' | '), '· card export:', await page.locator('text=Exportación · Factura E').count())
await shot('02-factura-e-ver')
// 3. Tilde ARCA apagado: comprobante interno
await page.goto(`${BASE}/comprobantes/nuevo`); await idle()
const cli2 = page.locator('input[placeholder^="Buscar cliente"]'); await cli2.click(); await cli2.fill('Constru'); await page.waitForTimeout(500); await page.keyboard.press('Enter'); await page.waitForTimeout(300)
await page.locator('label:has-text("Informar a ARCA") input').uncheck(); await page.waitForTimeout(150)
await page.click('button:has-text("Agregar")'); const art2 = page.locator('input[placeholder^="Buscar artículo"]').first(); await art2.click(); await art2.fill('are'); await page.waitForTimeout(500); await page.keyboard.press('Enter'); await page.waitForTimeout(300)
console.log('  aviso interno:', await page.locator('text=Se emite como comprobante interno').count())
await page.click('button:has-text("Emitir")'); await idle(); await page.waitForTimeout(600)
console.log('  interno:', (await page.locator('h1.page-title').textContent()).replace(/\s+/g, ' ').trim(), '·', await page.locator('text=Interno · no informado a ARCA').count())
await shot('03-interno')
// 4. Remito: botón COT por WS (sin clave: no aparece)
await page.goto(`${BASE}/configuracion/impuestos`); await idle()
console.log('  bloque ARBA:', await page.locator('text=ARBA · COT por web service').count())
// 5. Importar: perfil
await page.goto(`${BASE}/configuracion/importar`); await idle()
console.log('  perfiles:', (await page.locator('select.input >> nth=1').locator('option').allTextContents()).join(' | '))
// 6. Sueldos F.931 y dictado
await page.goto(`${BASE}/sueldos`); await idle(); console.log('  F.931:', await page.locator('a:has-text("F.931")').count())
await page.locator('button[aria-label="Asistente"]').click(); await page.waitForTimeout(300); console.log('  micrófono asistente:', await page.locator('button[title="Dictar por voz"]').count())
// 7. Superadmin: IA y correo
await page.goto(`${BASE}/dashboard`); await idle(); await salir(page)
await _login(page, 'super@bigsys.com.ar')
await page.goto(`${BASE}/admin/sistema`); await idle()
console.log('  cards sistema:', await page.locator('h2:has-text("Inteligencia artificial")').count(), await page.locator('h2:has-text("Correo saliente")').count())
await page.fill('input[placeholder="sk-ant-…"]', 'sk-ant-prueba'); await page.locator('form:has(h2:has-text("Inteligencia artificial")) button:has-text("Guardar")').click(); await idle(); await page.waitForTimeout(400)
console.log('  guardado:', (await page.locator('.bg-emerald-50').first().textContent().catch(() => '')).trim().slice(0, 40), '· badge:', (await page.locator('form:has(h2:has-text("Inteligencia artificial")) .badge').textContent()).trim())
await shot('04-sistema-claves')
await fin(browser)
