// Fase 27.4: almacén con ubicaciones, pistola (guardar, consultar), preparación de pedidos y etiquetas.
import { abrir, idle as _idle, shot as _shot, login as _login, fin, BASE } from './lib.mjs'
const { browser, page } = await abrir()
const idle = () => _idle(page); const shot = n => _shot(page, 'alm-' + n)
const pre = 'Z' + String(Date.now()).slice(-4)
await _login(page, 'demo@bigsys.com.ar')
await page.click('button:has-text("Saltar")').catch(() => {})
await page.goto(`${BASE}/stock/almacen`); await idle()
await page.click('[data-e2e="tab-ubicaciones"]')
const g = page.locator('[data-e2e="generar"]')
await g.locator('input').nth(0).fill('A-B'); await g.locator('input').nth(1).fill('2'); await g.locator('input').nth(2).fill('1'); await g.locator('input').nth(3).fill(pre)
await g.locator('button:has-text("Generar")').click(); await idle(); await page.waitForTimeout(700)
console.log('  ubicaciones creadas:', await page.locator(`td.font-mono:has-text("${pre}-")`).count())
await shot('01-ubicaciones')
// Guardar algo sin ubicar con la pistola.
await page.click('[data-e2e="tab-sin"]'); await page.waitForTimeout(200)
const art = (await page.locator('tbody tr').first().locator('td').first().innerText()).trim()
await page.locator('tbody tr').first().locator('button:has-text("Guardar")').click(); await page.waitForTimeout(200)
await page.fill('[data-e2e="op-cantidad"]', '1')
await page.fill('[data-e2e="scan"]', `${pre}-A-01-1`); await page.press('[data-e2e="scan"]', 'Enter'); await page.waitForTimeout(700)
await page.click('[data-e2e="confirmar"]'); await page.waitForTimeout(1000)
console.log('  guardado:', (await page.locator('[data-e2e="msg"]').innerText()).trim())
// Consultar la ubicación.
await page.click('[data-e2e="modo-consultar"]')
await page.fill('[data-e2e="scan"]', `${pre}-A-01-1`); await page.press('[data-e2e="scan"]', 'Enter'); await page.waitForTimeout(700)
console.log('  la ubicación tiene:', (await page.locator('[data-e2e="resultado"] tbody tr').first().innerText()).replace(/\s+/g, ' ').trim(), '· esperado:', art.split('\n')[0])
await shot('02-pistola')
await page.click('[data-e2e="tab-preparar"]'); await page.locator('button:has(span.font-medium)').first().click(); await page.waitForTimeout(900)
console.log('  hoja de preparación:', await page.locator('[data-e2e="preparacion"] a:has-text("Imprimir hoja")').count() === 1)
await shot('03-preparar')
await page.goto(`${BASE}/stock/almacen/etiquetas`); await idle(); await page.waitForTimeout(500)
console.log('  etiquetas con código de barras:', await page.locator('[data-e2e="hoja-ubicaciones"] canvas').count())
await shot('04-etiquetas')
await fin(browser)
